/**
 * Repo Watch — mock snapshot.
 *
 * A realistic `RepoWatchSnapshot` shaped EXACTLY like the live
 * `/v1/repo-watch/snapshot` response (`@openscout/runtime`): agents carry a
 * broker `state` (live derives from "active"), sessions carry `source`+`harness`,
 * file `status` is the backend's human label ("untracked" | "conflict" |
 * "staged" | "unstaged" | "staged+unstaged"), project stats include change
 * sums, and `lastCommitAt` is epoch **milliseconds**.
 *
 * It deliberately exercises the full surface: all five attention levels,
 * dirty main, merge conflicts, diverged/detached, a scan error, attached live +
 * idle agents, long and empty file lists, and snapshot warnings.
 *
 * Timestamps are fixed (no wall-clock) so screenshots are byte-stable. Derive
 * "ago" via `agoFromMillis(t, snapshot.generatedAt)`.
 */

import type { RepoWatchSnapshot } from "./types";

/** Fixed generation instant (epoch ms) — ~2026-06-03. */
export const GENERATED_AT = 1_780_250_400_000;
const mins = (m: number) => GENERATED_AT - m * 60_000;
const hrs = (h: number) => GENERATED_AT - h * 3_600_000;
const days = (d: number) => GENERATED_AT - d * 86_400_000;

export const MOCK_SNAPSHOT: RepoWatchSnapshot = {
  generatedAt: GENERATED_AT,
  warnings: [
    "Tail discovery skipped 2 transcript roots outside the scan budget (OPENSCOUT_REPO_WATCH_SCAN_BUDGET_MS=400).",
    "1 worktree could not be scanned (see talkie · detached-spike).",
  ],
  totals: {
    projects: 3,
    worktrees: 11,
    dirtyWorktrees: 6,
    conflictedWorktrees: 1,
    attentionWorktrees: 3,
    attachedAgents: 5,
    attachedSessions: 5,
  },
  projects: [
    // ── openscout ────────────────────────────────────────────────────
    {
      id: "repo:openscout",
      name: "openscout",
      root: "/Users/arach/dev/openscout",
      commonGitDir: "/Users/arach/dev/openscout/.git",
      attention: "critical",
      attentionReasons: ["3 conflicted files", "Dirty main"],
      stats: {
        worktrees: 7,
        dirtyWorktrees: 5,
        conflictedWorktrees: 1,
        attachedAgents: 4,
        attachedSessions: 4,
        staged: 5,
        unstaged: 9,
        untracked: 6,
        conflicts: 3,
      },
      hints: [
        { path: "/Users/arach/dev/openscout", source: "endpoint", sourceLabel: "endpoint:scout-web" },
      ],
      worktrees: [
        {
          id: "worktree:openscout-main",
          path: "/Users/arach/dev/openscout",
          name: "openscout",
          isBare: false,
          branch: {
            name: "main",
            upstream: "origin/main",
            head: "dcb1d843",
            detached: false,
            ahead: 0,
            behind: 3,
            isMain: true,
            diverged: false,
          },
          status: {
            clean: false,
            staged: 0,
            unstaged: 2,
            untracked: 1,
            conflicts: 0,
            changedFiles: 3,
            files: [
              { path: "packages/runtime/src/broker.ts", status: "unstaged" },
              { path: "docs/eng/sco-061-repo-watch-worktree-state.md", status: "unstaged" },
              { path: ".env.local", status: "untracked" },
            ],
          },
          diff: {
            unstagedShortstat: "2 files changed, 41 insertions(+), 6 deletions(-)",
            stagedShortstat: null,
          },
          attention: "attention",
          attentionReasons: ["Dirty main", "3 behind origin/main"],
          agents: [],
          sessions: [],
          hints: [],
          lastCommitAt: hrs(5),
          scannedAt: GENERATED_AT,
          error: null,
        },
        {
          id: "worktree:openscout-repo-watch",
          path: "/Users/arach/dev/openscout/.worktrees/repo-watch-snapshot",
          name: "repo-watch-snapshot",
          isBare: false,
          branch: {
            name: "codex/repo-watch-snapshot",
            upstream: "origin/codex/repo-watch-snapshot",
            head: "fb2c0236",
            detached: false,
            ahead: 7,
            behind: 0,
            isMain: false,
            diverged: false,
          },
          status: {
            clean: false,
            staged: 4,
            unstaged: 3,
            untracked: 2,
            conflicts: 0,
            changedFiles: 9,
            files: [
              { path: "packages/runtime/src/repo-watch/snapshot.ts", status: "staged" },
              { path: "packages/runtime/src/repo-watch/discovery.ts", status: "staged" },
              { path: "packages/runtime/src/repo-watch/git.ts", status: "unstaged" },
              { path: "packages/runtime/src/server/routes.ts", status: "unstaged" },
              { path: "packages/protocol/src/repo-watch.ts", status: "staged" },
              { path: "docs/eng/sco-061-repo-watch-worktree-state.md", status: "unstaged" },
              { path: "packages/runtime/test/repo-watch.test.ts", status: "untracked" },
              { path: "packages/runtime/src/repo-watch/budget.ts", status: "staged" },
              { path: ".scratch/notes.md", status: "untracked" },
            ],
          },
          diff: {
            unstagedShortstat: "3 files changed, 88 insertions(+), 12 deletions(-)",
            stagedShortstat: "4 files changed, 412 insertions(+)",
          },
          attention: "active",
          attentionReasons: ["7 changed files", "7 ahead", "Scout activity attached"],
          agents: [{ id: "codex", name: "Codex", state: "active", harness: "codex" }],
          sessions: [{ id: "s-codex-1", source: "codex", harness: "codex" }],
          hints: [
            {
              path: "/Users/arach/dev/openscout/.worktrees/repo-watch-snapshot",
              source: "endpoint",
              agentId: "codex",
              agentName: "Codex",
              agentState: "active",
              harness: "codex",
            },
          ],
          lastCommitAt: mins(4),
          scannedAt: GENERATED_AT,
          error: null,
        },
        {
          id: "worktree:openscout-channel-reply",
          path: "/Users/arach/dev/openscout/.worktrees/channel-reply",
          name: "channel-reply",
          isBare: false,
          branch: {
            name: "codex/channel-reply-lifecycle",
            upstream: "origin/codex/channel-reply-lifecycle",
            head: "7a91ee03",
            detached: false,
            ahead: 2,
            behind: 1,
            isMain: false,
            diverged: true,
          },
          status: {
            clean: false,
            staged: 1,
            unstaged: 1,
            untracked: 0,
            conflicts: 0,
            changedFiles: 2,
            files: [
              { path: "apps/desktop/src/core/pairing/runtime/bridge/router.ts", status: "staged" },
              { path: "apps/desktop/src/core/pairing/runtime/bridge/router.test.ts", status: "unstaged" },
            ],
          },
          diff: {
            unstagedShortstat: "1 file changed, 9 insertions(+), 2 deletions(-)",
            stagedShortstat: "1 file changed, 23 insertions(+), 1 deletion(-)",
          },
          attention: "attention",
          attentionReasons: ["Diverged from origin/codex/channel-reply-lifecycle"],
          agents: [{ id: "qb", name: "QB", state: "active", harness: "claude-code" }],
          sessions: [{ id: "s-qb-1", source: "claude-code", harness: "claude-code" }],
          hints: [],
          lastCommitAt: mins(22),
          scannedAt: GENERATED_AT,
          error: null,
        },
        {
          id: "worktree:openscout-control-plane",
          path: "/Users/arach/dev/openscout/.worktrees/control-plane",
          name: "control-plane",
          isBare: false,
          branch: {
            name: "codex/control-plane-foundation",
            upstream: "origin/codex/control-plane-foundation",
            head: "55a0d1c9",
            detached: false,
            ahead: 1,
            behind: 4,
            isMain: false,
            diverged: true,
          },
          status: {
            clean: false,
            staged: 0,
            unstaged: 2,
            untracked: 0,
            conflicts: 3,
            changedFiles: 5,
            files: [
              { path: "packages/runtime/src/control-plane/permissions.ts", status: "conflict" },
              { path: "packages/runtime/src/control-plane/index.ts", status: "conflict" },
              { path: "packages/protocol/src/control-plane.ts", status: "conflict" },
              { path: "packages/runtime/src/server/routes.ts", status: "unstaged" },
              { path: "packages/runtime/test/control-plane.test.ts", status: "unstaged" },
            ],
          },
          diff: {
            unstagedShortstat: "5 files changed, 64 insertions(+), 31 deletions(-)",
            stagedShortstat: null,
          },
          attention: "critical",
          attentionReasons: ["3 conflicted files"],
          agents: [{ id: "atlas", name: "Atlas", state: "idle", harness: "claude-code" }],
          sessions: [{ id: "s-atlas-1", source: "claude-code", harness: "claude-code" }],
          hints: [],
          lastCommitAt: mins(41),
          scannedAt: GENERATED_AT,
          error: null,
        },
        {
          id: "worktree:openscout-avatar",
          path: "/Users/arach/dev/openscout/.worktrees/avatar-component",
          name: "avatar-component",
          isBare: false,
          branch: {
            name: "refactor/avatar-component",
            upstream: null,
            head: "0bde3652",
            detached: false,
            ahead: 0,
            behind: 0,
            isMain: false,
            diverged: false,
          },
          status: {
            clean: false,
            staged: 0,
            unstaged: 1,
            untracked: 3,
            conflicts: 0,
            changedFiles: 4,
            files: [
              { path: "packages/web/client/components/Avatar.tsx", status: "unstaged" },
              { path: "packages/web/client/components/Avatar.css", status: "untracked" },
              { path: "packages/web/client/components/Avatar.test.tsx", status: "untracked" },
              { path: "design/studio/components/AgentPresenceDot.tsx", status: "untracked" },
            ],
          },
          diff: {
            unstagedShortstat: "1 file changed, 14 insertions(+), 3 deletions(-)",
            stagedShortstat: null,
          },
          attention: "active",
          attentionReasons: ["4 changed files"],
          agents: [],
          sessions: [],
          hints: [],
          lastCommitAt: hrs(2),
          scannedAt: GENERATED_AT,
          error: null,
        },
        {
          id: "worktree:openscout-run-graphs",
          path: "/Users/arach/dev/openscout/.worktrees/run-graphs",
          name: "run-graphs",
          isBare: false,
          branch: {
            name: "codex/sco-007-run-graphs-recipes",
            upstream: "origin/codex/sco-007-run-graphs-recipes",
            head: "a2f0aa62",
            detached: false,
            ahead: 3,
            behind: 0,
            isMain: false,
            diverged: false,
          },
          status: {
            clean: true,
            staged: 0,
            unstaged: 0,
            untracked: 0,
            conflicts: 0,
            changedFiles: 0,
            files: [],
          },
          diff: { unstagedShortstat: null, stagedShortstat: null },
          attention: "active",
          attentionReasons: ["3 ahead", "Scout activity attached"],
          agents: [{ id: "ranger", name: "Ranger", state: "active", harness: "claude-code" }],
          sessions: [{ id: "s-ranger-1", source: "claude-code", harness: "claude-code" }],
          hints: [],
          lastCommitAt: mins(12),
          scannedAt: GENERATED_AT,
          error: null,
        },
        {
          id: "worktree:openscout-local-main-snapshot",
          path: "/Users/arach/dev/openscout/.worktrees/local-main-snapshot",
          name: "local-main-snapshot",
          isBare: false,
          branch: {
            name: "arach/local-main-snapshot",
            upstream: "origin/arach/local-main-snapshot",
            head: "92284ec5",
            detached: false,
            ahead: 0,
            behind: 0,
            isMain: false,
            diverged: false,
          },
          status: {
            clean: true,
            staged: 0,
            unstaged: 0,
            untracked: 0,
            conflicts: 0,
            changedFiles: 0,
            files: [],
          },
          diff: { unstagedShortstat: null, stagedShortstat: null },
          attention: "quiet",
          attentionReasons: [],
          agents: [],
          sessions: [],
          hints: [],
          lastCommitAt: days(2),
          scannedAt: GENERATED_AT,
          error: null,
        },
      ],
    },

    // ── hudson ───────────────────────────────────────────────────────
    {
      id: "repo:hudson",
      name: "hudson",
      root: "/Users/arach/dev/hudson",
      commonGitDir: "/Users/arach/dev/hudson/.git",
      attention: "active",
      attentionReasons: ["Scout activity attached", "7 changed files"],
      stats: {
        worktrees: 2,
        dirtyWorktrees: 1,
        conflictedWorktrees: 0,
        attachedAgents: 1,
        attachedSessions: 1,
        staged: 2,
        unstaged: 4,
        untracked: 1,
        conflicts: 0,
      },
      hints: [
        { path: "/Users/arach/dev/hudson", source: "endpoint", agentId: "hudson", agentName: "Hudson", agentState: "active" },
      ],
      worktrees: [
        {
          id: "worktree:hudson-main",
          path: "/Users/arach/dev/hudson",
          name: "hudson",
          isBare: false,
          branch: {
            name: "feat/app-settings-config",
            upstream: "origin/feat/app-settings-config",
            head: "907dd74c",
            detached: false,
            ahead: 5,
            behind: 0,
            isMain: false,
            diverged: false,
          },
          status: {
            clean: false,
            staged: 2,
            unstaged: 4,
            untracked: 1,
            conflicts: 0,
            changedFiles: 7,
            files: [
              { path: "src/settings/useAppSettings.ts", status: "unstaged" },
              { path: "src/settings/AppSettingsConfig.ts", status: "unstaged" },
              { path: "src/shell/HudsonApp.tsx", status: "unstaged" },
              { path: "src/theme/tokens.css", status: "unstaged" },
              { path: "src/controls/Toggle.tsx", status: "staged" },
              { path: "src/controls/SegmentedControl.tsx", status: "staged" },
              { path: "src/controls/Toggle.css", status: "untracked" },
            ],
          },
          diff: {
            unstagedShortstat: "4 files changed, 53 insertions(+), 18 deletions(-)",
            stagedShortstat: "2 files changed, 96 insertions(+)",
          },
          attention: "active",
          attentionReasons: ["7 changed files", "5 ahead", "Scout activity attached"],
          agents: [{ id: "hudson", name: "Hudson", state: "active", harness: "claude-code" }],
          sessions: [{ id: "s-hudson-1", source: "claude-code", harness: "claude-code" }],
          hints: [],
          lastCommitAt: mins(2),
          scannedAt: GENERATED_AT,
          error: null,
        },
        {
          id: "worktree:hudson-release",
          path: "/Users/arach/dev/hudson/.worktrees/release-0-2",
          name: "release-0-2",
          isBare: false,
          branch: {
            name: "release/0.2.0",
            upstream: "origin/release/0.2.0",
            head: "1f9a7b03",
            detached: false,
            ahead: 0,
            behind: 0,
            isMain: false,
            diverged: false,
          },
          status: {
            clean: true,
            staged: 0,
            unstaged: 0,
            untracked: 0,
            conflicts: 0,
            changedFiles: 0,
            files: [],
          },
          diff: { unstagedShortstat: null, stagedShortstat: null },
          attention: "quiet",
          attentionReasons: [],
          agents: [],
          sessions: [],
          hints: [],
          lastCommitAt: days(1),
          scannedAt: GENERATED_AT,
          error: null,
        },
      ],
    },

    // ── talkie ───────────────────────────────────────────────────────
    {
      id: "repo:talkie",
      name: "talkie",
      root: "/Users/arach/dev/talkie",
      commonGitDir: "/Users/arach/dev/talkie/.git",
      attention: "unknown",
      attentionReasons: ["Could not read Git status"],
      stats: {
        worktrees: 2,
        dirtyWorktrees: 0,
        conflictedWorktrees: 0,
        attachedAgents: 0,
        attachedSessions: 0,
        staged: 0,
        unstaged: 0,
        untracked: 0,
        conflicts: 0,
      },
      hints: [
        { path: "/Users/arach/dev/talkie", source: "environment", sourceLabel: "OPENSCOUT_REPO_WATCH_ROOTS" },
      ],
      worktrees: [
        {
          id: "worktree:talkie-main",
          path: "/Users/arach/dev/talkie",
          name: "talkie",
          isBare: false,
          branch: {
            name: "main",
            upstream: "origin/main",
            head: "e4d2b8a1",
            detached: false,
            ahead: 0,
            behind: 0,
            isMain: true,
            diverged: false,
          },
          status: {
            clean: true,
            staged: 0,
            unstaged: 0,
            untracked: 0,
            conflicts: 0,
            changedFiles: 0,
            files: [],
          },
          diff: { unstagedShortstat: null, stagedShortstat: null },
          attention: "quiet",
          attentionReasons: [],
          agents: [],
          sessions: [],
          hints: [],
          lastCommitAt: days(4),
          scannedAt: GENERATED_AT,
          error: null,
        },
        {
          id: "worktree:talkie-detached-spike",
          path: "/Users/arach/dev/talkie/.worktrees/detached-spike",
          name: "detached-spike",
          isBare: false,
          branch: {
            name: null,
            upstream: null,
            head: "9c1d77af",
            detached: true,
            ahead: 0,
            behind: 0,
            isMain: false,
            diverged: false,
          },
          status: {
            clean: true,
            staged: 0,
            unstaged: 0,
            untracked: 0,
            conflicts: 0,
            changedFiles: 0,
            files: [],
          },
          diff: { unstagedShortstat: null, stagedShortstat: null },
          attention: "unknown",
          attentionReasons: ["Could not read Git status"],
          agents: [],
          sessions: [],
          hints: [],
          lastCommitAt: null,
          scannedAt: GENERATED_AT,
          error: "Could not read Git status",
        },
      ],
    },
  ],
};
