export const SCOUT_ELECTRON_CHANNELS = {
  getAppInfo: "scout:get-app-info",
  getShellState: "scout:get-shell-state",
  refreshShellState: "scout:refresh-shell-state",
  getAppSettings: "scout:get-app-settings",
  updateAppSettings: "scout:update-app-settings",
  retireProject: "scout:retire-project",
  restoreProject: "scout:restore-project",
  runOnboardingCommand: "scout:run-onboarding-command",
  skipOnboarding: "scout:skip-onboarding",
  restartOnboarding: "scout:restart-onboarding",
  getAgentConfig: "scout:get-agent-config",
  updateAgentConfig: "scout:update-agent-config",
  pickDirectory: "scout:pick-directory",
  quitApp: "scout:quit-app",
  revealPath: "scout:reveal-path",
  getPhonePreparation: "scout:get-phone-preparation",
  updatePhonePreparation: "scout:update-phone-preparation",
  getPairingState: "scout:get-pairing-state",
  refreshPairingState: "scout:refresh-pairing-state",
  controlPairingService: "scout:control-pairing-service",
  updatePairingConfig: "scout:update-pairing-config",
  restartAgent: "scout:restart-agent",
  sendRelayMessage: "scout:send-relay-message",
  controlBroker: "scout:control-broker",
  getAgentSession: "scout:get-agent-session",
  openAgentSession: "scout:open-agent-session",
  toggleVoiceCapture: "scout:toggle-voice-capture",
  setVoiceRepliesEnabled: "scout:set-voice-replies-enabled",
  getLogCatalog: "scout:get-log-catalog",
  getBrokerInspector: "scout:get-broker-inspector",
  readLogSource: "scout:read-log-source",
} as const;

export type ScoutElectronChannelName =
  typeof SCOUT_ELECTRON_CHANNELS[keyof typeof SCOUT_ELECTRON_CHANNELS];
