// QRScannerView — Camera-based QR code scanner using AVFoundation.
//
// UIViewControllerRepresentable wrapping AVCaptureSession.
// Scans for QR codes, validates the Dispatch pairing payload (from
// Security/QRPayload.swift), and returns the result via a callback.

import SwiftUI
import AVFoundation

// MARK: - Scanner View

struct QRScannerView: UIViewControllerRepresentable {
    let onScan: (Result<QRPayload, QRScanError>) -> Void

    func makeUIViewController(context: Context) -> QRScannerViewController {
        QRScannerViewController(onScan: onScan)
    }

    func updateUIViewController(_ uiViewController: QRScannerViewController, context: Context) {}
}

// MARK: - Scanner ViewController

/// Errors specific to the QR scanning process (distinct from QRPayloadError
/// which covers parsing/validation of the payload itself).
enum QRScanError: LocalizedError {
    case invalidJSON
    case validationFailed(String)

    var errorDescription: String? {
        switch self {
        case .invalidJSON:
            "Could not read QR code. Make sure it was generated by the current bridge pairing command."
        case .validationFailed(let reason):
            reason
        }
    }
}

final class QRScannerViewController: UIViewController, @preconcurrency AVCaptureMetadataOutputObjectsDelegate {
    private let captureSession = AVCaptureSession()
    private var previewLayer: AVCaptureVideoPreviewLayer?
    private let onScan: (Result<QRPayload, QRScanError>) -> Void
    private var hasProcessed = false

    init(onScan: @escaping (Result<QRPayload, QRScanError>) -> Void) {
        self.onScan = onScan
        super.init(nibName: nil, bundle: nil)
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) { fatalError() }

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .black
        setupCamera()
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        previewLayer?.frame = view.bounds
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if !captureSession.isRunning {
            DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                self?.captureSession.startRunning()
            }
        }
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        if captureSession.isRunning {
            DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                self?.captureSession.stopRunning()
            }
        }
    }

    private func setupCamera() {
        guard let videoCaptureDevice = AVCaptureDevice.default(for: .video),
              let videoInput = try? AVCaptureDeviceInput(device: videoCaptureDevice) else {
            return
        }

        if captureSession.canAddInput(videoInput) {
            captureSession.addInput(videoInput)
        }

        let metadataOutput = AVCaptureMetadataOutput()
        if captureSession.canAddOutput(metadataOutput) {
            captureSession.addOutput(metadataOutput)
            metadataOutput.setMetadataObjectsDelegate(self, queue: .main)
            metadataOutput.metadataObjectTypes = [.qr]
        }

        let preview = AVCaptureVideoPreviewLayer(session: captureSession)
        preview.frame = view.bounds
        preview.videoGravity = .resizeAspectFill
        view.layer.addSublayer(preview)
        previewLayer = preview

        // Add scanning overlay
        addScanningOverlay()
    }

    private func addScanningOverlay() {
        // Dimmed overlay with transparent cutout
        let overlayView = ScannerOverlayView()
        overlayView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(overlayView)

        NSLayoutConstraint.activate([
            overlayView.topAnchor.constraint(equalTo: view.topAnchor),
            overlayView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            overlayView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            overlayView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
        ])
    }

    // MARK: - AVCaptureMetadataOutputObjectsDelegate

    func metadataOutput(
        _ output: AVCaptureMetadataOutput,
        didOutput metadataObjects: [AVMetadataObject],
        from connection: AVCaptureConnection
    ) {
        guard !hasProcessed else { return }

        guard let metadataObject = metadataObjects.first as? AVMetadataMachineReadableCodeObject,
              metadataObject.type == .qr,
              let stringValue = metadataObject.stringValue else {
            return
        }

        hasProcessed = true

        // Haptic feedback
        let generator = UIImpactFeedbackGenerator(style: .medium)
        generator.impactOccurred()

        // Parse and validate using the canonical QRPayload from Security/
        guard let payload = try? QRPayload.parse(from: stringValue) else {
            onScan(.failure(.invalidJSON))
            return
        }

        if let validationError = payload.validate() {
            onScan(.failure(.validationFailed(validationError)))
            return
        }

        onScan(.success(payload))
    }
}

// MARK: - Overlay View

private final class ScannerOverlayView: UIView {
    private let cutoutSize: CGFloat = 250

    override init(frame: CGRect) {
        super.init(frame: frame)
        backgroundColor = .clear
        isOpaque = false
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) { fatalError() }

    override func draw(_ rect: CGRect) {
        guard let ctx = UIGraphicsGetCurrentContext() else { return }

        // Dimmed background
        ctx.setFillColor(UIColor.black.withAlphaComponent(0.55).cgColor)
        ctx.fill(rect)

        // Clear cutout
        let cutoutRect = CGRect(
            x: (rect.width - cutoutSize) / 2,
            y: (rect.height - cutoutSize) / 2 - 40,
            width: cutoutSize,
            height: cutoutSize
        )

        let path = UIBezierPath(roundedRect: cutoutRect, cornerRadius: 16)
        ctx.setBlendMode(.clear)
        ctx.addPath(path.cgPath)
        ctx.fillPath()

        // Corner brackets
        ctx.setBlendMode(.normal)
        let bracketColor = UIColor.white.withAlphaComponent(0.9)
        ctx.setStrokeColor(bracketColor.cgColor)
        ctx.setLineWidth(3)
        ctx.setLineCap(.round)

        let bracketLength: CGFloat = 30
        let r = cutoutRect
        let corners: [(CGPoint, CGPoint, CGPoint)] = [
            // Top-left
            (CGPoint(x: r.minX, y: r.minY + bracketLength),
             CGPoint(x: r.minX, y: r.minY),
             CGPoint(x: r.minX + bracketLength, y: r.minY)),
            // Top-right
            (CGPoint(x: r.maxX - bracketLength, y: r.minY),
             CGPoint(x: r.maxX, y: r.minY),
             CGPoint(x: r.maxX, y: r.minY + bracketLength)),
            // Bottom-left
            (CGPoint(x: r.minX, y: r.maxY - bracketLength),
             CGPoint(x: r.minX, y: r.maxY),
             CGPoint(x: r.minX + bracketLength, y: r.maxY)),
            // Bottom-right
            (CGPoint(x: r.maxX - bracketLength, y: r.maxY),
             CGPoint(x: r.maxX, y: r.maxY),
             CGPoint(x: r.maxX, y: r.maxY - bracketLength)),
        ]

        for (start, corner, end) in corners {
            ctx.move(to: start)
            ctx.addLine(to: corner)
            ctx.addLine(to: end)
            ctx.strokePath()
        }
    }
}
