export const C = {
  bg: 'var(--os-bg)',
  surface: 'var(--os-surface)',
  border: 'var(--os-border)',
  ink: 'var(--os-ink)',
  muted: 'var(--os-muted)',
  accent: 'var(--os-accent)',
  accentBg: 'var(--os-accent-bg)',
  accentBorder: 'var(--os-accent-border)',
  tagBg: 'var(--os-tag-bg)',
  logoBg: 'var(--os-logo-bg)',
  logoBorder: 'var(--os-logo-border)',
  termBg: 'var(--os-terminal-bg)',
  termFg: 'var(--os-terminal-fg)',
  markBg: 'var(--os-mark-bg)',
  markFg: 'var(--os-mark-fg)',
  radiusXs: 'var(--os-radius-xs)',
  radiusSm: 'var(--os-radius-sm)',
  radiusMd: 'var(--os-radius-md)',
  radiusLg: 'var(--os-radius-lg)',
  radiusXl: 'var(--os-radius-xl)',
  shadowXs: 'var(--os-shadow-xs)',
  shadowSm: 'var(--os-shadow-sm)',
  shadowMd: 'var(--os-shadow-md)',
  shadowLg: 'var(--os-shadow-lg)',
} as const;
