import { describe, expect, test } from "bun:test";

import type { Agent } from "../../lib/types.ts";
import {
  agentLaneHorizonWindowMs,
  buildAgentLanes,
  createStableLaneOrder,
  hasDesignedAgentCard,
  isAutoGeneratedLaneAgentName,
  isAgentLaneWorking,
  laneContextLabel,
  lanePrimaryLabel,
  laneStatusLabel,
  observeDataFromTail,
  resolveTranscriptAttribution,
  sortLanesWithStableOrder,
  type AgentLane,
} from "./agent-lanes-model.ts";

const NOW = 1_700_000_000_000;

function lane(overrides: Partial<AgentLane> & { agent: Agent }): AgentLane {
  return {
    id: overrides.agent.id,
    source: "scout",
    observe: null,
    lastActiveAt: NOW - 5_000,
    current: true,
    ...overrides,
  };
}

describe("lane display labels", () => {
  test("uses project for auto-generated native session names", () => {
    const agent = stubAgent("Grok 0f8eddbb");
    agent.agentClass = "organic";
    agent.harness = "grok";
    agent.project = "openscout";

    expect(isAutoGeneratedLaneAgentName(agent)).toBe(true);
    expect(hasDesignedAgentCard(agent, "native")).toBe(false);
    expect(lanePrimaryLabel(agent, "native")).toBe("openscout");
    expect(laneStatusLabel(agent, "native")).toBe("grok");
    expect(laneContextLabel(agent, "native")).toBe("grok");
  });

  test("keeps deliberate scout agent card names", () => {
    const agent = stubAgent("openscout-card");
    agent.project = "openscout";
    agent.harness = "codex";
    agent.harnessSessionId = "sess-codex-live";

    expect(isAutoGeneratedLaneAgentName(agent)).toBe(false);
    expect(hasDesignedAgentCard(agent, "scout")).toBe(true);
    expect(lanePrimaryLabel(agent, "scout")).toBe("openscout-card");
    expect(laneStatusLabel(agent, "scout")).toBe("codex");
    expect(laneContextLabel(agent, "scout")).toBe("openscout");
  });
});

describe("isAgentLaneWorking", () => {
  test("excludes in-flight scout agents without substantive trace activity", () => {
    const agent: Agent = {
      id: "agent:alpha",
      name: "alpha",
      handle: null,
      agentClass: "managed",
      harness: "claude",
      state: "in_flight",
      projectRoot: null,
      cwd: null,
      updatedAt: NOW - 3 * 60_000,
      createdAt: null,
      transport: null,
      selector: null,
      wakePolicy: null,
      capabilities: [],
      project: null,
      branch: null,
      role: null,
      model: null,
      harnessSessionId: "claude-hung-session",
      harnessLogPath: null,
      conversationId: "conv-1",
      homeNodeId: null,
      homeNodeName: null,
      ownerId: null,
      ownerName: null,
      ownerHandle: null,
    };

    expect(isAgentLaneWorking(lane({
      agent,
      lastActiveAt: NOW - 3 * 60_000,
      observe: null,
    }), NOW)).toBe(false);
  });

  test("includes in-flight scout agents with recent substantive observe activity", () => {
    const agent: Agent = {
      id: "agent:alpha",
      name: "alpha",
      handle: null,
      agentClass: "managed",
      harness: "codex",
      state: "in_flight",
      projectRoot: null,
      cwd: null,
      updatedAt: NOW,
      createdAt: null,
      transport: null,
      selector: null,
      wakePolicy: null,
      capabilities: [],
      project: null,
      branch: null,
      role: null,
      model: null,
      harnessSessionId: "sess-live",
      harnessLogPath: null,
      conversationId: "conv-1",
      homeNodeId: null,
      homeNodeName: null,
      ownerId: null,
      ownerName: null,
      ownerHandle: null,
    };

    expect(isAgentLaneWorking(lane({
      agent,
      lastActiveAt: NOW - 15_000,
      observe: {
        events: [{
          id: "evt-1",
          t: 15,
          kind: "tool",
          text: "grep pattern",
          tool: "grep",
        }],
        files: [],
        live: true,
        metadata: {
          session: {
            sessionStart: NOW - 15_000,
          },
        },
      },
    }), NOW)).toBe(true);
  });

  test("excludes organic processes without substantive observe activity", () => {
    const agent: Agent = {
      id: "harness:codex:1234",
      name: "codex",
      handle: null,
      agentClass: "organic",
      harness: "codex",
      state: "working",
      projectRoot: "/tmp/repo",
      cwd: "/tmp/repo",
      updatedAt: NOW,
      createdAt: null,
      transport: null,
      selector: null,
      wakePolicy: null,
      capabilities: [],
      project: "repo",
      branch: null,
      role: null,
      model: null,
      harnessSessionId: null,
      harnessLogPath: null,
      conversationId: "harness:1234",
      homeNodeId: null,
      homeNodeName: null,
      ownerId: null,
      ownerName: null,
      ownerHandle: null,
    };

    expect(isAgentLaneWorking(lane({ agent }), NOW)).toBe(false);
  });

  test("includes lanes with recent tool activity in observe", () => {
    const agent: Agent = {
      id: "harness:codex:5678",
      name: "codex",
      handle: null,
      agentClass: "organic",
      harness: "codex",
      state: "working",
      projectRoot: "/tmp/repo",
      cwd: "/tmp/repo",
      updatedAt: NOW,
      createdAt: null,
      transport: null,
      selector: null,
      wakePolicy: null,
      capabilities: [],
      project: "repo",
      branch: null,
      role: null,
      model: null,
      harnessSessionId: "sess-1",
      harnessLogPath: "/tmp/sess.jsonl",
      conversationId: "sess-1",
      homeNodeId: null,
      homeNodeName: null,
      ownerId: null,
      ownerName: null,
      ownerHandle: null,
    };

    expect(isAgentLaneWorking(lane({
      agent,
      lastActiveAt: NOW - 120_000,
      observe: {
        events: [{
          id: "evt-1",
          t: 120,
          kind: "tool",
          text: "grep pattern",
          tool: "grep",
        }],
        files: [],
        live: true,
        metadata: {
          session: {
            sessionStart: NOW - 120_000,
          },
        },
      },
    }), NOW)).toBe(true);
  });

  test("respects the selected activity window", () => {
    const agent = stubAgent("alpha");
    agent.state = "callable";
    const staleLane = lane({
      agent,
      lastActiveAt: NOW - 20 * 60_000,
      observe: {
        events: [{
          id: "evt-1",
          t: 612,
          kind: "tool",
          text: "grep pattern",
          tool: "grep",
        }],
        files: [],
        live: false,
        metadata: {
          session: {
            sessionStart: NOW - 3 * 60 * 60_000,
          },
        },
      },
    });

    expect(isAgentLaneWorking(staleLane, NOW, agentLaneHorizonWindowMs("5m"))).toBe(false);
    expect(isAgentLaneWorking(staleLane, NOW, agentLaneHorizonWindowMs("30m"))).toBe(false);
  });

  test("excludes transcript mtime-only lanes without substantive tail events", () => {
    const lanes = buildAgentLanes({
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "019edd5a-ad7c-7563-8b28-a9d34699a369",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
  });

  test("includes native codex lanes with recent substantive tail events", () => {
    const lanes = buildAgentLanes({
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "019edd5a-ad7c-7563-8b28-a9d34699a369",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [stubTailEvent("019edd5a-ad7c-7563-8b28-a9d34699a369", NOW - 15_000, "tool")],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("native");
    expect(lanes[0]?.agent.harness).toBe("codex");
  });

  test("includes native grok lanes with recent phase activity", () => {
    const lanes = buildAgentLanes({
      transcripts: [{
        source: "grok",
        transcriptPath: "/Users/art/.grok/sessions/%2FUsers%2Fart%2Fdev%2Fopenscout/sess-grok/events.jsonl",
        sessionId: "sess-grok",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      tailEvents: [
        stubTailEvent("sess-grok", NOW - 10_000, "system", {
          source: "grok",
          summary: "phase · streaming_reasoning",
        }),
      ],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("native");
    expect(lanes[0]?.agent.harness).toBe("grok");
  });

  test("does not let a scout-managed process from another source claim a native transcript", () => {
    const lanes = buildAgentLanes({
      transcripts: [{
        source: "grok",
        transcriptPath: "/Users/art/.grok/sessions/%2FUsers%2Fart%2Fdev%2Fopenscout/sess-grok/events.jsonl",
        sessionId: "sess-grok",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 20_000,
        size: 1200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [
        stubTailEvent("sess-grok", NOW - 10_000, "system", {
          source: "grok",
          summary: "phase · streaming_reasoning",
        }),
      ],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.agent.harness).toBe("grok");
  });

  test("excludes scout-managed transcripts from native lanes", () => {
    const lanes = buildAgentLanes({
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "sess-codex-live",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 15_000,
        size: 2200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [stubTailEvent("sess-codex-live", NOW - 10_000, "tool")],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
    expect(resolveTranscriptAttribution({
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-codex-live",
      cwd: "/Users/art/dev/openscout",
      project: "openscout",
      harness: "unattributed",
      mtimeMs: NOW,
      size: 1,
    }, [{
      pid: 42,
      ppid: 1,
      command: "codex app-server",
      etime: "01:00",
      cwd: "/Users/art/dev/openscout",
      harness: "scout-managed",
      parentChain: [],
      source: "codex",
    }])).toBe("scout-managed");
  });

  test("includes scout codex agents when substantive tail events are fresh but observe is stale", () => {
    const agent = stubAgent("openscout-card");
    agent.harnessSessionId = "sess-codex-live";
    agent.state = "callable";
    agent.updatedAt = NOW - 3 * 60 * 60_000;

    const lanes = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "sess-codex-live",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 15_000,
        size: 2200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [stubTailEvent("sess-codex-live", NOW - 12_000, "tool")],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("scout");
    expect(lanes[0]?.agent.id).toBe(agent.id);
  });

  test("prefers the scout lane when it owns a session with fresh substantive tail events", () => {
    const agent = stubAgent("openscout-card");
    agent.harnessSessionId = "sess-codex-live";
    agent.state = "callable";
    agent.updatedAt = NOW - 3 * 60 * 60_000;

    const lanes = buildAgentLanes({
      scoutAgents: [agent],
      transcripts: [{
        source: "codex",
        transcriptPath: "/tmp/rollout.jsonl",
        sessionId: "sess-codex-live",
        cwd: "/Users/art/dev/openscout",
        project: "openscout",
        harness: "unattributed",
        mtimeMs: NOW - 10_000,
        size: 2200,
      }],
      processes: [{
        pid: 42,
        ppid: 1,
        command: "codex app-server",
        etime: "01:00",
        cwd: "/Users/art/dev/openscout",
        harness: "scout-managed",
        parentChain: [],
        source: "codex",
      }],
      tailEvents: [stubTailEvent("sess-codex-live", NOW - 8_000, "assistant")],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(1);
    expect(lanes[0]?.source).toBe("scout");
    expect(lanes[0]?.agent.id).toBe(agent.id);
  });

  test("filters grok streaming noise and maps tool names from summaries", () => {
    const transcript = {
      source: "grok",
      transcriptPath: "/tmp/grok.jsonl",
      sessionId: "sess-grok",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const data = observeDataFromTail(transcript, [
      {
        id: "phase",
        ts: NOW - 5_000,
        source: "grok",
        sessionId: "sess-grok",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "system",
        summary: "phase · streaming_text",
      },
      {
        id: "read",
        ts: NOW - 3_000,
        source: "grok",
        sessionId: "sess-grok",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "tool",
        summary: "Read started",
      },
      {
        id: "shell",
        ts: NOW - 1_000,
        source: "grok",
        sessionId: "sess-grok",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "tool-result",
        summary: "Shell completed · success",
      },
    ], true);

    expect(data.events.map((event) => event.text)).toEqual([
      "Read started",
      "Shell completed · success",
    ]);
    expect(data.events[0]?.tool).toBe("Read");
    expect(data.events[1]?.tool).toBe("Shell");
    expect(data.events[0]?.detail).toBeUndefined();
  });

  test("maps tail event timestamps into lane observe metadata", () => {
    const transcript = {
      source: "codex",
      transcriptPath: "/tmp/rollout.jsonl",
      sessionId: "sess-1",
      cwd: "/repo",
      project: "repo",
      harness: "unattributed" as const,
      mtimeMs: NOW,
      size: 100,
    };
    const data = observeDataFromTail(transcript, [
      {
        id: "e1",
        ts: NOW - 4_000,
        source: "codex",
        sessionId: "sess-1",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "tool",
        summary: "grep foo",
      },
      {
        id: "e2",
        ts: NOW - 1_000,
        source: "codex",
        sessionId: "sess-1",
        pid: 1,
        parentPid: null,
        project: "repo",
        cwd: "/repo",
        harness: "unattributed",
        kind: "assistant",
        summary: "done",
      },
    ], true);

    expect(data.metadata?.session?.sessionStart).toBe(NOW - 4_000);
    expect(data.events[1]?.t).toBe(3);
  });

  test("excludes stale observe history even when poll metadata is fresh", () => {
    const agent = stubAgent("dewey");
    agent.state = "callable";
    agent.updatedAt = NOW;

    const lanes = buildAgentLanes({
      scoutAgents: [agent],
      observeCache: {
        [agent.id]: {
          source: "history",
          fidelity: "timestamped",
          historyPath: "/tmp/dewey.jsonl",
          sessionId: "sess-dewey",
          updatedAt: NOW,
          data: {
            events: [{
              id: "evt-1",
              t: 612,
              kind: "message",
              text: "old reply",
              to: "human",
            }],
            files: [],
            live: true,
            metadata: {
              session: {
                sessionStart: NOW - 3 * 60 * 60_000,
              },
            },
          },
        },
      },
      transcripts: [],
      tailEvents: [],
      now: NOW,
      horizon: "5m",
    });

    expect(lanes).toHaveLength(0);
  });
});

describe("sortLanesWithStableOrder", () => {
  test("keeps existing lanes in first-seen order as activity timestamps change", () => {
    const order = createStableLaneOrder();
    const alpha = lane({ agent: stubAgent("alpha") });
    const beta = lane({ agent: stubAgent("beta"), lastActiveAt: NOW - 60_000 });

    const first = sortLanesWithStableOrder([alpha, beta], order);
    expect(first.lanes.map((item) => item.id)).toEqual(["agent:alpha", "agent:beta"]);

    const bumpedBeta = { ...beta, lastActiveAt: NOW + 30_000 };
    const staleAlpha = { ...alpha, lastActiveAt: NOW - 120_000 };
    const second = sortLanesWithStableOrder([bumpedBeta, staleAlpha], order);
    expect(second.lanes.map((item) => item.id)).toEqual(["agent:alpha", "agent:beta"]);
    expect(second.newLaneIds).toEqual([]);
  });

  test("appends newly working agents at the end", () => {
    const order = createStableLaneOrder();
    const alpha = lane({ agent: stubAgent("alpha") });
    sortLanesWithStableOrder([alpha], order);

    const gamma = lane({ agent: stubAgent("gamma") });
    const result = sortLanesWithStableOrder([alpha, gamma], order);
    expect(result.lanes.map((item) => item.id)).toEqual(["agent:alpha", "agent:gamma"]);
    expect(result.newLaneIds).toEqual(["agent:gamma"]);
  });

  test("re-admits returning agents at the end after they leave the roster", () => {
    const order = createStableLaneOrder();
    const alpha = lane({ agent: stubAgent("alpha") });
    sortLanesWithStableOrder([alpha], order);
    sortLanesWithStableOrder([], order);

    const result = sortLanesWithStableOrder([alpha], order);
    expect(result.lanes.map((item) => item.id)).toEqual(["agent:alpha"]);
    expect(result.newLaneIds).toEqual(["agent:alpha"]);
  });
});

function stubTailEvent(
  sessionId: string,
  ts: number,
  kind: "tool" | "assistant" | "user" | "tool-result" | "system",
  overrides: Partial<import("../../lib/types.ts").TailEvent> = {},
): import("../../lib/types.ts").TailEvent {
  return {
    id: `evt:${sessionId}:${ts}`,
    ts,
    source: "codex",
    sessionId,
    pid: 1,
    parentPid: null,
    project: "openscout",
    cwd: "/Users/art/dev/openscout",
    harness: "unattributed",
    kind,
    summary: "grep foo",
    ...overrides,
  };
}

function stubAgent(name: string): Agent {
  return {
    id: `agent:${name}`,
    name,
    handle: null,
    agentClass: "managed",
    harness: "codex",
    state: "callable",
    projectRoot: null,
    cwd: null,
    updatedAt: NOW,
    createdAt: null,
    transport: null,
    selector: null,
    wakePolicy: null,
    capabilities: [],
    project: null,
    branch: null,
    role: null,
    model: null,
    harnessSessionId: null,
    harnessLogPath: null,
    conversationId: `${name}-conv`,
    homeNodeId: null,
    homeNodeName: null,
    ownerId: null,
    ownerName: null,
    ownerHandle: null,
  };
}
