import type { ObserveCacheEntry } from "../../lib/observe.ts";
import {
  filterTailEventsForDisplay,
  observeToolFieldsFromTailEvent,
  tailObserveEventDetail,
} from "../../lib/tail-display.ts";
import type {
  Agent,
  ObserveData,
  ObserveEvent,
  TailDiscoveredProcess,
  TailDiscoveredTranscript,
  TailEvent,
  TailHarness,
} from "../../lib/types.ts";

export type AgentLaneHorizonKey = "5m" | "30m" | "4h" | "24h";

export const DEFAULT_AGENT_LANE_HORIZON: AgentLaneHorizonKey = "5m";

export const AGENT_LANE_HORIZON_OPTIONS: ReadonlyArray<{
  key: AgentLaneHorizonKey;
  label: string;
  windowMs: number;
}> = [
  { key: "5m", label: "5m", windowMs: 5 * 60_000 },
  { key: "30m", label: "30m", windowMs: 30 * 60_000 },
  { key: "4h", label: "4h", windowMs: 4 * 60 * 60_000 },
  { key: "24h", label: "24h", windowMs: 24 * 60 * 60_000 },
];

export function agentLaneHorizonWindowMs(horizon: AgentLaneHorizonKey): number {
  return AGENT_LANE_HORIZON_OPTIONS.find((option) => option.key === horizon)?.windowMs
    ?? AGENT_LANE_HORIZON_OPTIONS[0].windowMs;
}

export function agentLaneHorizonLabel(horizon: AgentLaneHorizonKey): string {
  return AGENT_LANE_HORIZON_OPTIONS.find((option) => option.key === horizon)?.label
    ?? horizon;
}

export type AgentLaneSource = "scout" | "native";

export type AgentLane = {
  id: string;
  agent: Agent;
  source: AgentLaneSource;
  observe: ObserveData | null;
  lastActiveAt: number;
  current: boolean;
};

function titleCaseHarness(value: string): string {
  return value ? `${value[0]?.toUpperCase()}${value.slice(1).toLowerCase()}` : "";
}

/** True for tail-synthesized names like "Grok 0f8eddbb" or "Codex 019edd5a". */
export function isAutoGeneratedLaneAgentName(agent: Agent): boolean {
  const name = agent.name.trim();
  if (!name) return true;
  if (agent.agentClass === "organic") return true;

  const harness = agent.harness?.trim();
  if (!harness) return false;

  const head = titleCaseHarness(harness);
  return new RegExp(`^${head}\\s+[0-9a-f]{6}`, "i").test(name);
}

/** Scout-managed cards with deliberate names — not harness+session placeholders. */
export function hasDesignedAgentCard(agent: Agent, source: AgentLaneSource): boolean {
  return source === "scout"
    && agent.agentClass !== "organic"
    && !isAutoGeneratedLaneAgentName(agent);
}

export function lanePrimaryLabel(agent: Agent, source: AgentLaneSource): string {
  if (hasDesignedAgentCard(agent, source)) {
    return agent.name.trim() || "Agent";
  }
  return agent.project?.trim() || agent.harness?.trim() || "local";
}

export function laneStatusLabel(agent: Agent, source: AgentLaneSource): string {
  return agent.harness?.trim() || lanePrimaryLabel(agent, source);
}

export function laneContextLabel(agent: Agent, source: AgentLaneSource): string {
  if (hasDesignedAgentCard(agent, source)) {
    return [agent.project, agent.branch].filter(Boolean).join(" · ") || agent.harness || "local";
  }
  const harness = agent.harness?.trim();
  const session = agent.harnessSessionId?.trim();
  if (harness && session) {
    return `${harness} · ${session.replace(/\.jsonl$/u, "").slice(0, 8)}`;
  }
  return harness || session?.slice(0, 8) || "native";
}

const NATIVE_DISCOVERED_FRESH_MS = 5 * 60_000;

function stableHash(value: string): string {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(36);
}

export function nativeSessionId(transcript: TailDiscoveredTranscript): string {
  const sessionId = transcript.sessionId?.trim() || "session";
  return `native:${transcript.source}:${sessionId}:${stableHash(transcript.transcriptPath)}`;
}

function tailEventKindToObserveKind(kind: TailEvent["kind"]): ObserveEvent["kind"] {
  switch (kind) {
    case "assistant":
      return "message";
    case "tool":
    case "tool-result":
      return "tool";
    case "user":
      return "ask";
    case "system":
      return "system";
    default:
      return "note";
  }
}

/** Build lane observe data from the tail firehose (wall-clock timestamps). */
export function observeDataFromTail(
  transcript: TailDiscoveredTranscript,
  events: TailEvent[],
  current: boolean,
): ObserveData {
  const tail = filterTailEventsForDisplay(
    [...events].sort((left, right) => left.ts - right.ts),
    "work",
  ).slice(-48);
  const sessionStart = tail[0]?.ts ?? transcript.mtimeMs;

  const observeEvents = tail.map((event): ObserveEvent => {
    const toolFields = observeToolFieldsFromTailEvent(event);
    return {
      id: event.id,
      t: Math.max(0, Math.round((event.ts - sessionStart) / 1000)),
      kind: tailEventKindToObserveKind(event.kind),
      text: event.summary,
      tool: toolFields.tool,
      arg: toolFields.arg,
      result: toolFields.result,
      detail: tailObserveEventDetail(event, transcript),
      live: current && event.id === tail[tail.length - 1]?.id,
    };
  });

  const placeholderEvents: ObserveEvent[] = observeEvents.length > 0
    ? observeEvents
    : (Date.now() - transcript.mtimeMs <= NATIVE_DISCOVERED_FRESH_MS
        ? [{
            id: `${nativeSessionId(transcript)}:discovered`,
            t: 0,
            kind: "system",
            text: `Native ${transcript.source} transcript discovered.`,
            detail: transcript.cwd ?? transcript.transcriptPath,
          }]
        : []);

  return {
    events: placeholderEvents,
    files: [],
    live: current && observeEvents.length > 0,
    metadata: {
      session: {
        cwd: transcript.cwd,
        externalSessionId: transcript.sessionId,
        sessionStart,
      },
    },
  };
}

/** @deprecated Use observeDataFromTail — kept for call-site compatibility. */
export function nativeObserveData(
  transcript: TailDiscoveredTranscript,
  events: TailEvent[],
  current: boolean,
): ObserveData {
  return observeDataFromTail(transcript, events, current);
}

function titleCase(value: string): string {
  return value ? `${value[0]?.toUpperCase()}${value.slice(1)}` : "Native";
}

function shortId(value: string | null | undefined): string {
  if (!value) return "session";
  return value.replace(/\.jsonl$/u, "").slice(0, 8);
}

export function nativeSessionAgent(
  transcript: TailDiscoveredTranscript,
  lastActiveAt: number,
  current: boolean,
): Agent {
  const sessionId = transcript.sessionId?.trim() || null;
  const name = `${titleCase(transcript.source)} ${shortId(sessionId)}`;
  return {
    id: nativeSessionId(transcript),
    name,
    handle: null,
    agentClass: "organic",
    harness: transcript.source,
    state: current ? "working" : "idle",
    projectRoot: transcript.cwd,
    cwd: transcript.cwd,
    updatedAt: lastActiveAt,
    createdAt: null,
    transport: null,
    selector: null,
    wakePolicy: null,
    capabilities: [],
    project: transcript.project,
    branch: null,
    role: null,
    model: null,
    harnessSessionId: sessionId,
    harnessLogPath: transcript.transcriptPath,
    conversationId: sessionId ?? nativeSessionId(transcript),
    homeNodeId: null,
    homeNodeName: null,
    ownerId: null,
    ownerName: null,
    ownerHandle: null,
  };
}

function observeEventWallMs(
  event: ObserveEvent,
  sessionStartMs: number | undefined,
): number | null {
  if (!Number.isFinite(event.t) || event.t < 0) return null;
  if (typeof sessionStartMs !== "number" || !Number.isFinite(sessionStartMs)) return null;
  return sessionStartMs + event.t * 1000;
}

export function observeLastSubstantiveActivityAt(
  observe: ObserveData | null | undefined,
): number | null {
  if (!observe) return null;

  const sessionStart = observe.metadata?.session?.sessionStart;
  let latest: number | null = null;

  for (const event of observe.events) {
    if (!isSubstantiveObserveEvent(event)) continue;
    const wallMs = observeEventWallMs(event, sessionStart);
    if (wallMs === null) continue;
    latest = latest === null ? wallMs : Math.max(latest, wallMs);
  }

  if (typeof sessionStart === "number" && Number.isFinite(sessionStart)) {
    for (const file of observe.files) {
      if (!Number.isFinite(file.lastT) || file.lastT < 0) continue;
      const wallMs = sessionStart + file.lastT * 1000;
      latest = latest === null ? wallMs : Math.max(latest, wallMs);
    }
  }

  return latest;
}

function hasLiveSubstantiveWork(observe: ObserveData | null | undefined): boolean {
  if (!observe?.live) return false;
  return observe.events.some(
    (event) => event.live === true && isSubstantiveObserveEvent(event),
  );
}

function hasRecentSubstantiveObserve(
  observe: ObserveData | null | undefined,
  now: number,
  windowMs: number,
): boolean {
  const lastAt = observeLastSubstantiveActivityAt(observe);
  if (lastAt === null) return false;
  return now - lastAt <= windowMs;
}

function laneActivityAt(
  agent: Agent,
  observeEntry: ObserveCacheEntry | undefined,
  now: number,
): number {
  if (hasLiveSubstantiveWork(observeEntry?.data)) {
    return now;
  }

  const observeAt = observeLastSubstantiveActivityAt(observeEntry?.data);
  const agentAt = agent.updatedAt ?? 0;

  if (observeAt !== null) {
    return Math.max(observeAt, agentAt);
  }

  return 0;
}

export function isAgentLaneLive(
  observe: ObserveData | null | undefined,
): boolean {
  return hasLiveSubstantiveWork(observe);
}

const PLACEHOLDER_EVENT_MARKERS = [
  "transcript discovered",
  "waiting for events",
  "no session trace",
  "waiting for a live session",
];

function isSubstantiveObserveEvent(event: ObserveEvent): boolean {
  if (event.kind === "tool" || event.kind === "think" || event.kind === "ask" || event.kind === "message") {
    return true;
  }
  if (event.kind === "note") return true;
  if (event.kind === "system" || event.kind === "boot") {
    const text = event.text.trim().toLowerCase();
    return !PLACEHOLDER_EVENT_MARKERS.some((marker) => text.includes(marker));
  }
  return false;
}

const ATTRIBUTION_RANK: Record<TailHarness, number> = {
  "scout-managed": 3,
  "hudson-managed": 2,
  unattributed: 1,
};

/** File-discovered transcripts default to unattributed; resolve from live processes. */
export function resolveTranscriptAttribution(
  transcript: TailDiscoveredTranscript,
  processes: TailDiscoveredProcess[],
): TailHarness {
  const cwd = transcript.cwd?.trim();
  if (!cwd) return transcript.harness;

  const matches = processes.filter((proc) => proc.source === transcript.source && proc.cwd === cwd);
  if (matches.length === 0) return transcript.harness;

  return matches.reduce((best, candidate) => {
    const bestRank = ATTRIBUTION_RANK[best.harness] ?? 0;
    const candRank = ATTRIBUTION_RANK[candidate.harness] ?? 0;
    if (candRank > bestRank) return candidate;
    if (candRank === bestRank && candidate.pid < best.pid) return candidate;
    return best;
  }).harness;
}

function isSubstantiveTailEvent(event: TailEvent): boolean {
  if (event.kind === "tool"
    || event.kind === "tool-result"
    || event.kind === "assistant"
    || event.kind === "user") {
    return true;
  }

  if (event.kind !== "system") return false;
  if (event.source === "grok") {
    return /^(turn |loop |phase · |first token|permission )/u.test(event.summary);
  }
  if (event.source === "cursor") {
    return event.summary.startsWith("process sample");
  }
  return false;
}

function hasRecentSubstantiveTailEvents(
  events: TailEvent[],
  now: number,
  windowMs: number,
): boolean {
  return events.some((event) => {
    if (now - event.ts > windowMs) return false;
    return isSubstantiveTailEvent(event);
  });
}

function sessionSubstantiveLastActiveAt(
  sessionId: string | null | undefined,
  eventsBySession: Map<string, TailEvent[]>,
): number {
  const normalized = sessionId?.trim();
  if (!normalized) return 0;

  const events = eventsBySession.get(normalized) ?? [];
  let latest = 0;
  for (const event of events) {
    if (!isSubstantiveTailEvent(event)) continue;
    latest = Math.max(latest, event.ts);
  }
  return latest;
}

function hasNativeLaneWorkingSignal(
  events: TailEvent[],
  now: number,
  windowMs: number,
): boolean {
  return hasRecentSubstantiveTailEvents(events, now, windowMs);
}

/** True when the lane represents an agent actively doing work within the horizon. */
export function isAgentLaneWorking(
  lane: AgentLane,
  now: number = Date.now(),
  windowMs: number = agentLaneHorizonWindowMs(DEFAULT_AGENT_LANE_HORIZON),
  sessionSubstantiveAt = 0,
): boolean {
  const { agent, observe, lastActiveAt, source } = lane;
  if (lastActiveAt <= 0 || now - lastActiveAt > windowMs) {
    return false;
  }

  if (source === "native") {
    return hasLiveSubstantiveWork(observe)
      || hasRecentSubstantiveObserve(observe, now, windowMs);
  }

  if (sessionSubstantiveAt > 0 && now - sessionSubstantiveAt <= windowMs) {
    return true;
  }

  if (hasLiveSubstantiveWork(observe)) {
    return true;
  }

  if (hasRecentSubstantiveObserve(observe, now, windowMs)) {
    return true;
  }

  return false;
}

function compareLanesById(a: AgentLane, b: AgentLane): number {
  return a.id.localeCompare(b.id);
}

export type StableLaneOrder = {
  slots: Map<string, number>;
  nextSlot: number;
};

export function createStableLaneOrder(): StableLaneOrder {
  return { slots: new Map(), nextSlot: 0 };
}

/** Keep lane columns in first-seen order; new lanes append at the end. */
export function sortLanesWithStableOrder(
  lanes: AgentLane[],
  order: StableLaneOrder,
): { lanes: AgentLane[]; newLaneIds: string[] } {
  const newLaneIds: string[] = [];

  for (const lane of lanes) {
    if (!order.slots.has(lane.id)) {
      order.slots.set(lane.id, order.nextSlot);
      order.nextSlot += 1;
      newLaneIds.push(lane.id);
    }
  }

  const activeIds = new Set(lanes.map((lane) => lane.id));
  for (const id of [...order.slots.keys()]) {
    if (!activeIds.has(id)) order.slots.delete(id);
  }

  const sorted = [...lanes].sort((left, right) => {
    const slotLeft = order.slots.get(left.id) ?? Number.MAX_SAFE_INTEGER;
    const slotRight = order.slots.get(right.id) ?? Number.MAX_SAFE_INTEGER;
    if (slotLeft !== slotRight) return slotLeft - slotRight;
    return compareLanesById(left, right);
  });

  return { lanes: sorted, newLaneIds };
}

export function buildAgentLanes(input: {
  transcripts: TailDiscoveredTranscript[];
  tailEvents: TailEvent[];
  processes?: TailDiscoveredProcess[];
  scoutAgents?: Agent[];
  observeCache?: Record<string, ObserveCacheEntry | undefined>;
  now: number;
  workingOnly?: boolean;
  horizon?: AgentLaneHorizonKey;
  /** @deprecated Pass scoutAgents instead. */
  agents?: Agent[];
}): AgentLane[] {
  const {
    transcripts,
    tailEvents,
    processes = [],
    scoutAgents = input.agents ?? [],
    observeCache = {},
    now,
    workingOnly = true,
    horizon = DEFAULT_AGENT_LANE_HORIZON,
  } = input;
  const windowMs = agentLaneHorizonWindowMs(horizon);
  const lanes: AgentLane[] = [];
  const seenIds = new Set<string>();
  const claimedSessionIds = new Set<string>();

  const eventsBySession = new Map<string, TailEvent[]>();
  for (const event of tailEvents) {
    const bucket = eventsBySession.get(event.sessionId) ?? [];
    bucket.push(event);
    eventsBySession.set(event.sessionId, bucket);
  }

  const scoutBySession = new Map<string, Agent>();
  for (const agent of scoutAgents) {
    const sessionId = agent.harnessSessionId?.trim();
    if (!sessionId || scoutBySession.has(sessionId)) continue;
    scoutBySession.set(sessionId, agent);
  }

  // Tail-first: transcripts + live events drive lane roster.
  for (const transcript of transcripts) {
    const attribution = resolveTranscriptAttribution(transcript, processes);
    if (attribution === "scout-managed" || attribution === "hudson-managed") continue;
    const sessionId = transcript.sessionId?.trim();
    const events = sessionId ? eventsBySession.get(sessionId) ?? [] : [];
    const lastActiveAt = sessionSubstantiveLastActiveAt(sessionId, eventsBySession);
    const current = lastActiveAt > 0 && now - lastActiveAt <= windowMs;
    if (!current || !hasNativeLaneWorkingSignal(events, now, windowMs)) {
      continue;
    }

    const scoutAgent = sessionId ? scoutBySession.get(sessionId) : undefined;
    const observe = observeDataFromTail(transcript, events, current);
    const sessionSubstantiveAt = lastActiveAt;

    if (scoutAgent) {
      const lane: AgentLane = {
        id: scoutAgent.id,
        agent: { ...scoutAgent, updatedAt: lastActiveAt },
        source: "scout",
        observe,
        lastActiveAt,
        current,
      };
      if (workingOnly && !isAgentLaneWorking(lane, now, windowMs, sessionSubstantiveAt)) {
        continue;
      }
      lanes.push(lane);
      seenIds.add(scoutAgent.id);
      if (sessionId) claimedSessionIds.add(sessionId);
      continue;
    }

    const laneId = nativeSessionId(transcript);
    if (seenIds.has(laneId)) continue;

    const agent = nativeSessionAgent(transcript, lastActiveAt, current);
    lanes.push({
      id: laneId,
      agent,
      source: "native",
      observe,
      lastActiveAt,
      current,
    });
    seenIds.add(laneId);
    if (sessionId) claimedSessionIds.add(sessionId);
  }

  // Broker-only lanes: in-flight scout agents without a tail transcript match.
  for (const agent of scoutAgents) {
    if (seenIds.has(agent.id)) continue;
    const sessionId = agent.harnessSessionId?.trim();
    if (sessionId && claimedSessionIds.has(sessionId)) continue;

    const observeEntry = observeCache[agent.id];
    const sessionSubstantiveAt = sessionSubstantiveLastActiveAt(
      agent.harnessSessionId,
      eventsBySession,
    );
    const lastActiveAt = Math.max(laneActivityAt(agent, observeEntry, now), sessionSubstantiveAt);
    const current = lastActiveAt > 0 && now - lastActiveAt <= windowMs;
    const lane: AgentLane = {
      id: agent.id,
      agent,
      source: "scout",
      observe: observeEntry?.data ?? null,
      lastActiveAt,
      current,
    };
    if (workingOnly && !isAgentLaneWorking(lane, now, windowMs, sessionSubstantiveAt)) {
      continue;
    }
    lanes.push(lane);
    seenIds.add(agent.id);
    if (sessionId) claimedSessionIds.add(sessionId);
  }

  return lanes.sort(compareLanesById);
}
