const { contextBridge, ipcRenderer } = require("electron");

const openScoutDesktop = {
  isDesktop: true,
  getAppInfo: () => ipcRenderer.invoke("openscout:get-app-info"),
  getShellState: () => ipcRenderer.invoke("openscout:get-shell-state"),
  refreshShellState: () => ipcRenderer.invoke("openscout:refresh-shell-state"),
  getAppSettings: () => ipcRenderer.invoke("openscout:get-app-settings"),
  updateAppSettings: (input) => ipcRenderer.invoke("openscout:update-app-settings", input),
  runOnboardingCommand: (input) => ipcRenderer.invoke("openscout:run-onboarding-command", input),
  skipOnboarding: () => ipcRenderer.invoke("openscout:skip-onboarding"),
  restartOnboarding: () => ipcRenderer.invoke("openscout:restart-onboarding"),
  pickDirectory: () => ipcRenderer.invoke("openscout:pick-directory"),
  quitApp: () => ipcRenderer.invoke("openscout:quit-app"),
  getPhonePreparation: () => ipcRenderer.invoke("openscout:get-phone-preparation"),
  updatePhonePreparation: (input) => ipcRenderer.invoke("openscout:update-phone-preparation", input),
  getAgentConfig: (agentId) => ipcRenderer.invoke("openscout:get-agent-config", agentId),
  updateAgentConfig: (input) => ipcRenderer.invoke("openscout:update-agent-config", input),
  restartAgent: (input) => ipcRenderer.invoke("openscout:restart-agent", input),
  sendRelayMessage: (input) => ipcRenderer.invoke("openscout:send-relay-message", input),
  controlBroker: (action) => ipcRenderer.invoke("openscout:control-broker", action),
  getLogCatalog: () => ipcRenderer.invoke("openscout:get-log-catalog"),
  getBrokerInspector: () => ipcRenderer.invoke("openscout:get-broker-inspector"),
  readLogSource: (input) => ipcRenderer.invoke("openscout:read-log-source", input),
  getDispatchState: () => ipcRenderer.invoke("openscout:get-dispatch-state"),
  refreshDispatchState: () => ipcRenderer.invoke("openscout:refresh-dispatch-state"),
  controlDispatchService: (action) => ipcRenderer.invoke("openscout:control-dispatch-service", action),
  updateDispatchConfig: (input) => ipcRenderer.invoke("openscout:update-dispatch-config", input),
  getAgentSession: (agentId) => ipcRenderer.invoke("openscout:get-agent-session", agentId),
  openAgentSession: (agentId) => ipcRenderer.invoke("openscout:open-agent-session", agentId),
  toggleVoiceCapture: () => ipcRenderer.invoke("openscout:toggle-voice-capture"),
  setVoiceRepliesEnabled: (enabled) => ipcRenderer.invoke("openscout:set-voice-replies-enabled", enabled),
  revealPath: (filePath) => ipcRenderer.invoke("openscout:reveal-path", filePath),
};

contextBridge.exposeInMainWorld("openScoutDesktop", openScoutDesktop);
