/**
 * Projects the curated model worldview to publishable JSON.
 *
 *   bun scripts/generate-model-worldview.ts
 *
 * The TS picks (model-economics.ts) are the authority; this JSON is a
 * projection served at https://openscout.app/.well-known/model-worldview.json
 * so consumers (first: Linea) get pick changes as a data refresh, never a
 * code update. Never hand-edit the output — change the picks and rerun.
 *
 * Contract (schema 1): additive fields are free; bump `schema` only on a
 * breaking shape change, because consumers reject schemas they don't know
 * rather than guess at them.
 */
import { join } from "node:path";
import {
  POPULAR_MODEL_FAMILIES,
  inexpensiveCognitionPick,
} from "../src/model-economics.js";

const OUT = join(
  import.meta.dir,
  "../../../landing/openscout.app/public/.well-known/model-worldview.json",
);

const families = POPULAR_MODEL_FAMILIES.map((family) => {
  const pick = inexpensiveCognitionPick(family);
  return {
    id: pick.family,
    label: pick.label,
    inexpensive: pick.inexpensive,
    budgetFloor: pick.budgetFloor ?? null,
    note: pick.note ?? null,
    economics: pick.economics
      ? {
          input: pick.economics.input,
          output: pick.economics.output,
          context: pick.economics.context ?? null,
          structuredOutput: pick.economics.structuredOutput ?? null,
        }
      : null,
  };
});

const worldview = {
  $comment:
    "Published at https://openscout.app/.well-known/model-worldview.json. " +
    "Generated by `bun packages/agent-sessions/scripts/generate-model-worldview.ts` " +
    "from the curated picks in packages/agent-sessions/src/model-economics.ts — never hand-edit.",
  schema: 1,
  generatedAt: new Date().toISOString().slice(0, 10),
  source: "models.dev + curated FAMILY_TIER_PICKS",
  popularOrder: POPULAR_MODEL_FAMILIES,
  families,
};

await Bun.write(OUT, `${JSON.stringify(worldview, null, 2)}\n`);
console.log(`wrote ${OUT} (${families.length} families)`);
